- spec/url_validator_spec.rb
Fixes:
- Each it-block should refer to one test (#2)
- Expect .method? Style (#3)
> Fix styles on specs

- lib/validators/url_validator.rb
- spec/url_validator_spec.rb
> Add validation for scheme

- README.md
- lib/url_validator.rb
- lib/url_validator/locale/en.yml
- lib/url_validator/localization.rb
- lib/validators/url_validator.rb
replaced error message with `I18n.t("errors.messages.invalid_url")`
> Add I18n for error messages

- lib/validators/url_validator.rb
- spec/url_validator_spec.rb
Reverts riboseinc/url_validator#18
> Revert "Authority"

- gemfiles/common.gemfile
- gemfiles/rails-4.1.gemfile
- gemfiles/rails-4.2.gemfile
- gemfiles/rails-5.0.gemfile
- gemfiles/rails-5.1.gemfile
Remove unfortunate Rails dependency (Active Model is enough), extract common things to separate file.
> Fix and improve gemfiles used in Travis build matrix

- .travis.yml
- gemfiles/rails-4.0.gemfile
- gemfiles/rails-head.gemfile
Add more Ruby and Rails versions. Improve overall configuration quality.
> Enhance Travis build matrix

- README.adoc
> Fix usage examples in the README

- spec/spec_helper.rb
- spec/support/model.rb
- spec/url_validator_spec.rb
Test the validator primarily by using ActiveModel's `#validates` method.
> Reorganize specs

- lib/uri_format_validator/validators/uri_format_validator.rb
Improve code style, DRY, use throw & catch for control flow instead of raising exceptions. Continuation of #42.
> Refactor validation flow

- lib/uri_format_validator/validators/uri_format_validator.rb
> Fix typo in the option name

- .codeclimate.yml
- .rubocop.yml
- Gemfile
- uri_format_validator.gemspec
Switch back to Rubocop 0.49. Update Rubocop configs accordingly. The CodeClimate does not support 0.50 yet.
> Downgrade Rubocop

- CHANGELOG.adoc
- README.adoc
Include basic information on how to use this gem.
> Rewrite documentation

- README.adoc
- gemfiles/common.gemfile
- spec/spec_helper.rb
- uri_format_validator.gemspec
> Generate test coverage reports with CodeCov

- spec/spec_helper.rb
Disable CodeCov when tests are run locally.
> Fix CodeCov integration

- .rubocop.yml
- gemfiles/common.gemfile
- gemfiles/rails-4.0.gemfile
- gemfiles/rails-4.1.gemfile
- gemfiles/rails-4.2.gemfile
- gemfiles/rails-5.0.gemfile
- gemfiles/rails-5.1.gemfile
- gemfiles/rails-head.gemfile
Check code style in Travis-specific gemfiles located in `gemfiles` directory. Add some explanatory comment, remove unnecessary bundler's group assignments.
> Improve Travis-only gemfiles

- .hound.yml
- .rubocop.yml
This is required by Hound which runs Rubocop v0.51.
> Upgrade Rubocop configuration once again

- spec/uri_validator_spec.rb
Refactor and reorganize specs to make them cleaner, simpler, and more complete.
> Improve specs for `retrievability` option

- README.adoc
> Add instructions in README for Relish publishing

- .rubocop.tb.yml
- .rubocop.yml
- gemfiles/rails-4.0.gemfile
- gemfiles/rails-4.1.gemfile
- gemfiles/rails-4.2.gemfile
- gemfiles/rails-5.0.gemfile
- gemfiles/rails-5.1.gemfile
- gemfiles/rails-head.gemfile
- lib/uri_format_validator/util.rb
- spec/spec_helper.rb
- uri_format_validator.gemspec
There were some code style violations after Rubocop upgrade. Some issues are fixed, some cops overridden.
> Fix code style violations

- .travis.yml
- gemfiles/rails-5.2.gemfile
Test against recent versions of Ruby (2.5), and Rails (5.2).
> Upgrade Ruby and Rails
